name: sqflite_generator
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.1
  source_gen: ^1.4.0
  dart_style: ^2.3.2
  code_builder: ^4.7.0
  collection: ^1.17.2
  path: ^1.8.3
  glob: ^2.1.2
  sqflite_annotation:
    path: packages/sqflite_annotation

dev_dependencies:
  lints: ^2.0.1