targets:
  $default:
    builders:
      sqflite_model_builder:
        enabled: true
      # config_builder:
      #   enabled: true
      # checked_db_builder:
      #   enabled: true

builders:
  sqflite_model_builder:
    import: "package:sqflite_generator/sqflite_generator.dart"
    builder_factories: ["sqfliteModelBuilder"]
    build_extensions: { ".dart": [".sqflite_model_builder.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  # config_builder:
  #   import: "package:db_sql_generator/builder.dart"
  #   builder_factories: ["configBuilder"]
  #   build_extensions: { ".dart": [".config.dart"] }
  #   auto_apply: dependents
  #   build_to: source
  #   applies_builders: ["source_gen|combining_builder"]
  # checked_db_builder:
  #   import: "package:db_sql_generator/builder.dart"
  #   builder_factories: ["checkedBuilder"]
  #   runs_before: ["db_sql_generator|config_builder","db_sql_generator|model_builder"]
  #   build_extensions: { ".dart": [".sql_model.json"] }
  #   auto_apply: dependents
  #   build_to: cache