name: sqflite_generator
description: Sqflite annotation for Sqflite
version: 0.0.1
# publish_to: https://github.com/ho-doan/sqflite_generator
homepage: https://github.com/ho-doan/sqflite_generator

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.1
  source_gen: ^1.4.0
  dart_style: ^2.3.2
  code_builder: ^4.7.0
  collection: ^1.17.2
  path: ^1.8.3
  glob: ^2.1.2
  sqflite_annotation: ^0.0.1
    # path: ../sqflite_annotation
  change_case: ^2.0.1

dev_dependencies:
  lints: ^2.0.1